export const AUDIT_ACTIONS = {
  USER_INVITED: "USER_INVITED",
  USER_REINVITED: "USER_REINVITED",
  USER_ACTIVATED: "USER_ACTIVATED",
  USER_DISABLED: "USER_DISABLED",
  USER_ENABLED: "USER_ENABLED",
  ADMIN_GRANTED: "ADMIN_GRANTED",
  ADMIN_REVOKED: "ADMIN_REVOKED",
  ROOM_BOOKING_GRANTED: "ROOM_BOOKING_GRANTED",
  ROOM_BOOKING_REVOKED: "ROOM_BOOKING_REVOKED",
  BOOTSTRAP_ADMIN_CREATED: "BOOTSTRAP_ADMIN_CREATED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
